version: "3.9"

services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres12
    env_file:
      - ./.env
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq4
    env_file:
      - ./.env
    ports:
      - "5672:5672" # AMQP messaging port
      - "15672:15672" # Management UI port
  redis:
    image: redis:7.4-alpine
    container_name: redis7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ./.env
    ports:
      - "6380:6379"
