services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres12
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq4
    env_file:
      - ./.env
    ports:
      - "5672:5672" # AMQP messaging port
      - "15672:15672" # Management UI port
  gcloudpubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    container_name: gcloudpubsub-emulator
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    env_file:
      - ./.env
  redis:
    image: redis:7.4-alpine
    container_name: redis7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ./.env
    ports:
      - "6380:6379"
