version: "3.9"

services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres12_compose
    env_file:
      - ./.env
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq4
    env_file:
      - ./.env
    ports:
      - "5672:5672" # AMQP messaging port
      - "15672:15672" # Management UI port
